description:
  obstacle_num: 3
  target_num: 4

  target_0:
    period: 5
    x0_map: [-0.9,0.0,0.0]
    n_map: [0,0,1]
    d_map: [0.3,0.0,0.0]
    param: [1,2,1]

  target_1:
    period: 5
    x0_map: [-0.9,0.0,0.0]
    n_map: [0,0,1]
    d_map: [0.3,0.0,0.0]
    param: [2,0,1]

  target_2:
    period: 5
    x0_map: [-0.9,0.0,0.0]
    n_map: [0,0,1]
    d_map: [0.3,0.0,0.0]
    param: [1,0,1]

  target_3:
    period: 5
    x0_map: [-0.9,0.0,0.0]
    n_map: [0,0,1]
    d_map: [0.3,0.0,0.0]
    param: [1,1,1]

  obj_0:
    period: -10.0
    x0_map: [-0.5,0.2582,1.680]
    n_map: [1,0,0]
    d_map: [0,0,-0.4]
    r_fac: 0.5
    param: [0]

  obj_1:
    period: 15.0
    x0_map: [0.7,-1.0,0.6]
    n_map: [0,0,1]
    d_map: [0,0.9,0]
    r_fac: 1.0
    param: [2,1,2]

  obj_2:
    period: 30.0
    x0_map: [-1.0,-0.2,0.6]
    n_map: [1,0,0]
    d_map: [0,0,-0.4]
    r_fac: 0.6
    param: [1,1,1,0]